// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ContainerScssNamespace {
  export interface IContainerScss {
    one: string;
    root: string;
    three: string;
    two: string;
  }
}

declare const ContainerScssModule: ContainerScssNamespace.IContainerScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ContainerScssNamespace.IContainerScss;
};

export = ContainerScssModule;
